import { Bot, CheckCircle2, FileSearch, ShieldAlert, TriangleAlert, Wrench } from "lucide-react"
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"
import { Badge } from "@/components/ui/badge"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Separator } from "@/components/ui/separator"
import type { TriageEvidencePacket } from "@/lib/contracts"
import { decisionPresentation, displayRepresentativeIds, selectionPresentation } from "@/lib/presentation"

type Props = { packet: TriageEvidencePacket | null }

function List({ items, empty }: { items: string[]; empty: string }) {
  return items.length ? <ul className="space-y-1.5 text-sm text-slate-300">{items.map((item) => <li key={item} className="flex gap-2"><span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-sky-300" />{item}</li>)}</ul> : <p className="text-sm text-slate-500">{empty}</p>
}

function statusVariant(tone: string) { return tone === "positive" ? "positive" : tone === "warning" ? "warning" : tone === "critical" ? "critical" : "neutral" as const }

export function EvidenceReview({ packet }: Props) {
  if (!packet) return <Card className="flex min-h-[650px] items-center justify-center bg-slate-950/50"><CardContent className="max-w-md pt-5 text-center"><div className="mx-auto mb-4 flex h-14 w-14 items-center justify-center rounded-2xl border border-slate-700 bg-slate-900"><FileSearch className="h-7 w-7 text-sky-300" /></div><CardTitle>Start a safe evidence review.</CardTitle><CardDescription className="mt-2">The result will explain what the system can show, what remains uncertain, and why no action runs automatically.</CardDescription></CardContent></Card>
  const policy = packet.policy_decision
  const decision = decisionPresentation(policy.decision_state)
  const representativeIds = displayRepresentativeIds(packet)
  const selection = packet.representative_selection
  return <div className="space-y-4"><Card className="overflow-hidden border-sky-400/20 bg-gradient-to-br from-slate-950 via-slate-950 to-sky-950/35"><CardHeader className="space-y-3"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="mb-2 text-xs font-semibold uppercase tracking-[0.18em] text-sky-300">Evidence review</div><CardTitle className="text-xl">{decision.title}</CardTitle><CardDescription className="mt-2 max-w-2xl">{decision.description}</CardDescription></div><Badge variant={statusVariant(decision.tone)}>{decision.title}</Badge></div><Separator /></CardHeader><CardContent className="space-y-4"><Alert><ShieldAlert className="mr-2 inline h-4 w-4" /><AlertTitle className="inline">Human review required.</AlertTitle><AlertDescription className="inline"> No procedure will run automatically. This screen supports investigation; it does not diagnose, remediate, or take production action.</AlertDescription></Alert><div className="grid gap-4 lg:grid-cols-2"><Card className="bg-slate-900/55"><CardHeader><CardTitle className="text-sm uppercase tracking-[0.12em] text-slate-300">System conclusion</CardTitle><CardDescription>{decision.description}</CardDescription></CardHeader><CardContent className="space-y-4"><div><div className="mb-2 text-xs font-medium uppercase tracking-wide text-slate-500">Historical evidence the system can safely show</div><List items={policy.retained_precedent_ids} empty="No historical precedent is safe to show." /></div><div><div className="mb-2 text-xs font-medium uppercase tracking-wide text-slate-500">Facts that still need verification</div><List items={policy.missing_critical_facts} empty="None" /></div>{policy.conflict_summary ? <div className="rounded-lg border border-amber-300/25 bg-amber-300/10 p-3 text-sm text-amber-100">{policy.conflict_summary}</div> : null}</CardContent></Card><Card className="bg-slate-900/55"><CardHeader><CardTitle className="text-sm uppercase tracking-[0.12em] text-slate-300">Closest past example</CardTitle><CardDescription>{selectionPresentation(selection?.status)}</CardDescription></CardHeader><CardContent className="space-y-4"><div className="flex flex-wrap gap-2">{representativeIds.length ? representativeIds.map((id) => <Badge key={id} variant="neutral">{id}</Badge>) : <span className="text-sm text-slate-500">No example is displayed.</span>}</div>{selection ? <div className="rounded-lg border border-slate-800 bg-slate-950/60 p-3 text-xs leading-5 text-slate-400">{selection.trace_reason}</div> : null}</CardContent></Card></div></CardContent></Card>
    <div className="grid gap-4 lg:grid-cols-2"><Card className="bg-slate-950/70"><CardHeader><div className="flex items-center gap-2"><Wrench className="h-4 w-4 text-amber-200" /><CardTitle>Human review and suggested investigation</CardTitle></div><CardDescription>These are optional investigation materials for a human responder. They do not authorize a change, restart, configuration update, or other production action.</CardDescription></CardHeader><CardContent className="space-y-4"><div><div className="mb-2 text-xs font-medium uppercase tracking-wide text-slate-500">Suggested investigation material</div><List items={policy.candidate_procedure_ids} empty="No procedure is suggested." /></div><div className="rounded-xl border border-amber-300/30 bg-amber-300/10 p-3 text-sm text-amber-100"><strong>Review only.</strong> Procedure execution authorized: <strong>{String(packet.procedure_execution_authorized)}</strong></div></CardContent></Card>
      <Card className="bg-slate-950/70"><CardHeader><div className="flex items-center gap-2"><Bot className="h-4 w-4 text-sky-200" /><CardTitle>Supporting context from Superlinked SIE</CardTitle></div><CardDescription>This is advisory context only. It cannot change the system conclusion, missing facts, procedure posture, or no-execution limit.</CardDescription></CardHeader><CardContent className="space-y-3">{packet.semantic_advisory.status === "available" ? <><div className="flex items-center gap-2 text-sm font-semibold text-emerald-200"><CheckCircle2 className="h-4 w-4" />Advisory evidence available</div><List items={packet.semantic_advisory.candidate_evidence.map((candidate) => `${candidate.incident_id} · rank ${candidate.rank}`)} empty="No advisory candidates were returned." /></> : <div className="flex items-center gap-2 text-sm font-semibold text-amber-100"><TriangleAlert className="h-4 w-4" />Advisory evidence unavailable</div>}</CardContent></Card></div>
  </div>
}
